# Character Creation

## Basic Overview

1. Choose a class.
1. Sketch-out your character concept.
1. Select a race, background, and other features (optional). 
1. Assign starting attribute points to attributes.
1. Assign starting skill points to skills.
1. Purchase gear and/or abilities.
1. Complete character form.

## Choosing a Power Level

Implementations of OpenD10 will vary widely in power level. Some games will be about novice students learning the ways of the world, while others may feature demigods battling over the fate of the cosmos. Implementers set the power level by assigning a number of points at character creation. The following table suggests some limits for an average implementation:

| Tier | Description | Starting Attribute Points | Maximum Attribute Value Possible | Starting Skill Points | Experience Point Value of Tier Package | 
| ----- | ----- | ----- | ----- | ----- | ----- |
| 0 | NPCs | 200 | 30 | 50 | 2100 | 
| 1 | New Heroes | 225 | 50 | 125 | 2500 |
| 2 | Veteran Heroes | 250 | 50 | 200 | 2900 |
| 3 | Epic Heroes | 275 | 50 | 275 | 3300 |
| 4 | Legendary Heroes | 300 | 50 | 350 | 3700 |

This table assumes default values for experience points per attribute point, experience points per skill point, and so on. If you'd like to see or change these weights, see the system mechanics notebook on GitHub. This table assumes that all experience points are spent on attributes and skills. If you want your players to start with features, consider changing the point value of the tier package or lowering the starting numbers for skills and attributes.

## Classes, Races, and Backgrounds

Most implementations of OpenD10 will have a set of classes that fit the theme of that implementation. These may be mages and knights in a fantasy setting, spies and soldiers in contemporary settings, spaceship captains and temporal engineers in science-fiction settings, and so on. Classes should convey a sense of that character’s role on the team and be complementary with other classes to complete a wide variety of challenges. 

Classes are implemented as packages of skills and features. For example, a mage might have bonuses to magic skills and features that allow them access to supernatural (i.e. magical) abilities. Classes should be balanced against each other, so that no one class is significantly stronger or weaker than the others. To balance classes, ensure that the point values for the attributes, skills, and features they grant are equal. 

Races are optional additional packages describing a character’s heritage that may be offered as part of an implementation. A fantasy or space opera setting may have many races, while a contemporary setting would only have one or a very few. Races should be used to convey natural talents (such as darkvision or sensitivity to gravity) but not stereotypes (such as ‘Dwarves usually don’t do magic'). 

Backgrounds are another type of package that may allow a player to select from thematically appropriate origins for their character. Both races and backgrounds are implemented as packages of skills and features. These need not necessarily be balanced - instead deduct a number of points from their character creation pool equal to the cost of the race or background. 

## Attributes

All characters in OpenD10 share the same eight attributes regardless of implementation. 

## Skills

All characters in OpenD10 become skilled as a result of their experiences. These skills represent areas of particular expertise. 

###  Optional Rule: Proficiency

It is possible to have a proficiency-based skill system in an OpenD10 implementation. To do so: 

* Allow players to select a number of skills at character creation, and divide the available skill points among those skills.
* At character progression milestones, equally increment all selected skills. 

## Features

Features are the ways in which characters are exceptional. Some features are beneficial and cost character creation points, while others are detrimental and refund points. Some implementations may only allow features to be gained via class, background, and racial choices.

## Gear and Abilities

Gear is the generic name for a character’s possessions and represents tools that they have to enable them to solve certain problems more easily (or at all). A character’s starting gear is purchased by converting points from the character creation pool into credits. An example of a piece of gear could be a laser gun.

An ability is an inherent piece of 'gear' - some way that a character has to solve certain problems more easily (or at all). A character that could fire a laser beam from their eyes has an ability to do so. Abilities are purchased using experience points.

The cost of a piece of gear is normally derived from factors such as: 

* The bonus it confers to a check (the ‘quality’ of the gear), 
* How often that check will occur,
* Whether the gear is consumed when used,
* How available the gear or its constituent parts are, and so on.

The cost of a piece of gear is derived the same way as the cost for an ability, except that gear is discounted for the ability to be stolen, broken, etc. In OpenD10 GMs must be cautious about the amount of loot players obtain, as this can equate to unexpected experience point gain and impact game balance. 

## Complete the Character Form

Some of a character's parameters, like height and weight, are derived from their attributes. Others (such a defenses) come up so often that pre-calculating them can greatly accelerate game play. 