# Features

The following list of features is a suggestion which may be expanded upon or overridden in an OpenD10 implementation. 

```{python}
# Create Features Table
#| label: tbl-features
#| tbl-cap: Features
#| echo: false

from sysdef import *

# The examples here show how to derive the values of features based on the game
# balance mechanics of the world. For example, Darkvision gives a character a 
# bonus on visual perception checks that only applies when in low-light. This 
# is a fairly common but not ubiquitous occurrence, so we can price Darkvision 
# using the common feature discount in the system definitions file.

darkvision_price = round(buff_pricer(low_light) * (1 - common_feat_discount))

features_table = pd.DataFrame(
    {
    "Darkvision":{
        "Description":"You can see in dim light up to 15 meters away. Objects appear in hues of red and grey.",
        "Cost":f"Costs {darkvision_price}."
        },
    "Educated":{
    "Description":"You have spent some of your earnings improving yourself.",
    "Cost":f"Costs {credits_per_xp} credits per experience point gained."
        },
    "Exceptional Attribute":{
    "Description":"You are supernaturally talented in an attribute. You have an attribute score higher than the maximum allowable.",
    "Cost":f"Costs {2 * xp_per_attribute} per attribute point over the maximum."
        },
    "Ghost / AI":{
    "Description":"You exist on a different plane of existience. You will need some way to interact with the material plane, but dangers on the material plane may not affect you.",
    "Cost":f"Costs {xp_to_ghost}."
        },
    "Honorbound":{
    "Description":"You have sworn to follow a code of honor. Failure to do so may result in a decrease in supernatural ability, loss of status with a patron or faction, or worse.",
    "Cost":"Gain 3x the value of the code of honor."
        },
    "Invested":{
    "Description":"You have access to ongoing dividends from some source. You may earn bonus credits during event wrapups.",
    "Cost":f"Costs 1 per {0.2 * credits_per_xp} credits."
        },
    "Resilient":{
    "Description":"You are naturally hardier. You gain bonus hit points.",
    "Cost":f"Costs {0.5 * xp_per_attribute} per hit point gained."
        },
    "Specialized":{
    "Description":"You have specific training or experience within a skill. Confers a +10 bonus on checks where your specialization applied. May only be purchased once per skill.",
    "Cost":f"Costs {2.5 * xp_per_skill}."
        },
    "Supernatural":{
    "Description":"You are one of the rare individuals that has supernatural ability. Allows the character to train in a supernatural skill.",
    "Cost":f"Costs {xp_per_supernatural_class * len(supernatural_classes)}."
        },
    "Unregistered":{
    "Description":"You have no identity in most common societies. You will need a fake identity for many actions, but it will be harder for authorities to track you.",
    "Cost":"Gain 10."
        },
    "Unskilled":{
    "Description":"(Character Creation only). You've spent more time in life honing your natural talents rather than using them. You have fewer skill points to spend in character creation.",
    "Cost":f"Gain {xp_per_skill} times the number of skill points surrendered."
        },
    "Untalented":{
    "Description":"(Character Creation only). You're not as naturally as gifted as your peers. You have fewer attribute points to spend in character creation.",
    "Cost":f"Gain {xp_per_attribute} times the number of skill points surrendered."
    },
    "Wealthy":{
    "Description":"You have spent some of your time working or otherwise trading your skills for cash.",
    "Cost":f"Costs 1 per {credits_per_xp} credits."
    }
})

features_table = features_table.sort_index(axis=1).T 

display(md(tabulate(features_table,
           headers=["Name", "Description", "Value"])))
```

    **Design Note**: Because credits are a form of experience points in OpenD10, the Invested feature allows for characters to essentially gain experience points over time without actively adventuring. This feature should be limited to situations where an implementation's game balance takes this feature into account. 

## Codes of Honor

Values are assigned on a scale of 1-5 where:

* One (1) rarely limits the character's ability to behave however they want, and 
* Five (5) makes them incapable of doing anything other living in a controlled environment and assiduously adhering to their code.

Examples: 

* Pirate's Code (Value 1)
* Assassin's Code (Value 2)
* Chivalry (Value 3)
* Bushido (Value 3)
* Ascetic's Code (Value 4)
* Isolationism (Value 5)