# Combat
Initiative / Scene Order: Agility check. One round is six seconds.

On your turn, in any order:

* One movement
* One action
* Speak up to 3 seconds

On others’ turns: One reaction (once until your next turn)

### Common Combat Actions:

* Attack: Make an unarmed, melee, or ranged attack. Difficulty rating per weapon stats or defender's defense rating (whichever is highest).
* Dodge: Spend your turn avoiding damage. Double your Avoid defense rating.
* Grapple: Grapple an enemy combatant within reach. Strength or Agilty + Unarmed Combat check vs defense. If successful, see Grapple sub-section.
* Hold Action: You hold an action to occur on someone else's turn. On your turn you must clearly describe what action you are holding and what will trigger your action to occur. When the trigger occurs, you use your reaction to execute your held action. If your turn comes around before your held action is triggered, you lose your held action.
* Use Item: You use an item either on your person or in the environment you can access.

### Grapple
Defender’s move is zero while grappled. Attacker’s move is halved. Attacker must move defender to an adjacent square during any movement or release the grapple. Both attacker and defender have a -50 penalty to attacks against targets other than each other while the defender is conscious and resisting. You may not grapple something more than two scales larger or smaller than you.

### Ranged Attacks
Character Scale Ranges:

0-2m (point blank),
3-10m (short),
11-24m (medium),
25+ meters (long).

### Scale
Combat advantages derived from differences in size are represented using scale. Examples below are based on default size weighting.

Mechanics:

* Smaller scale combatants have a bonus to hit and a penalty to damage.
* Larger scale combatants have a penalty to hit and a bonus to damage.
* If an attacker is using a weapon of a different scale than theirs, use the weapon's scale instead.
* The bonus or penalty to hit is equal to 10 to the power of the difference in the combatant ratings.
* PCs suffer this same penalty when using a weapon not their scale (unless there is a control module attached, such as a gun on a capital ship).
* The bonus or penalty to damage is equal to a number of D10s equal to the difference in combat ratings.

#### Scale Ratings:

0: Tiny. Pixie, infant, rodent. Gear almost impossible to find.

1: Small. Child, dwarf, gnome, cat, dog. Gear harder to find.

2: Medium. Human, Elf, Orc.

3: Large. Troll, Ogre, Cyclops, Motorcycle. Gear harder to find.

4: Huge. Elephant, roc, young dragons, cars, wagons, dingies. Gear almost impossible to find.

5: Gargantuan. Whale, adult dragons, semi truck. Highest possible character scale.

6: Star Fighter. Star Fighters, Tanks.

7: Small Ships. Gunboats.

8 - 9: Medium Ships. Cargo Freighters, Star Freighters.

12: Large Ships. Cargo Container Ships, Cruise Ships, Capital Ships.

16: Planet.

22: Star.

```{python}
# Derive Scale Table
#| label: tbl-scale
#| fig-cap: "A table showing the average size of an organism at each scale."
#| echo: false

from sysdef import *

size = []
size.append(smallest_scale)

for i in range(25):
  size.append(size[i] * scale_scalar)

scale_data = {
    "Size (m)": size,
}

scale_table = pd.DataFrame(scale_data)

display(md(tabulate(scale_table, headers=["Scale", "Size(m)"])))
```

### Restoration
Mana Points are restored with food and rest. 1 MP is restored with consuming 100 calories of food and resting 5 minutes. For healthy organisms, after eating a full meal and getting a normal night of rest all MP are restored on awakening.

Hit Points restored naturally return at a rate of 1 HP per day of rest.